--TD TP SEANCE 4
--question 1, 91
SELECT NOMCLI
FROM CLI;

--question 2, 5
SELECT NOMCLI 
FROM CLI 
WHERE PAYS = 'France' ORDER BY NOMCLI;

--question 3, 9
SELECT NOMCLI 
FROM CLI 
WHERE PAYS = 'France' or PAYS = 'Royaume-Uni';

--question 4, 26
SELECT DISTINCT (NOMPRO)
FROM COM, DET, CLI, PRO
WHERE CLI.NUMCLI = COM.NUMCLI
AND COM.NUMCOM = DET.NUMCOM
AND DET.NUMPRO = PRO.NUMPRO
AND CLI.NOMCLI = 'Antonio';

--question 5, 73
SELECT NOMCLI
FROM CLI, COM
WHERE CLI.NUMCLI = COM.NUMCLI
AND (COM.ANCOM = 2002 OR COM.ANCOM = 2003);

--question 6, 13 SI <= 50 OU 11 SI < 50
SELECT DISTINCT NOMFOU --POURQUOI DISTINCT
FROM FOU, PRO
WHERE PRO.NUMFOU = FOU.NUMFOU
AND (PRO.PRIXUNIT < 50);

--question 7, Specialty, Plusspar
SELECT DISTINCT NOMFOU
FROM FOU, PRO
WHERE PRO.NUMFOU = FOU.NUMFOU
AND (PRO.PRIXUNIT < 50)

INTERSECT -- POURQUOI INTERSECT

SELECT DISTINCT NOMFOU
FROM FOU, PRO
WHERE PRO.NUMFOU = FOU.NUMFOU
AND (PRO.PRIXUNIT > 400);

--SELECT DISTINCT NOMFOU
--FROM FOU, PRO
--WHERE PRO.NUMFOU = FOU.NUMFOU
--AND (PRO.PRIXUNIT < 50 or PRO.PRIXUNIT > 400);

--question 8, 5
SELECT DISTINCT NUMFOU
FROM PRO
WHERE NOMPRO = 'Chef'
AND PRIXUNIT = (
    SELECT MIN(PRIXUNIT) 
    FROM PRO
    WHERE NOMPRO = 'Chef'
);

--question 12, PB Refresco
SELECT*
FROM FOU
WHERE NOMFOU NOT IN(
    SELECT F.NOMFOU
    FROM FOU F, PRO P
    WHERE F.NUMFOU = P.NUMPRO
    AND PRIXUNIT >= 50
);