(define (domain HANOI)
    (:requirements :strips)
    (:predicates
        (disk ?disk)
        (tower ?tower)

        (clear ?object)
        (on ?object_A ?object_B)
        (on_tower ?tower)
        (smaller ?object_A ?object_B)

        (tower_empty)
        (tower_full)
    )
    (:action remove_from_tower
        :parameters (?disk ?tower)
        :precondition (and
            (disk ?disk)
            (tower ?tower)
            (on ?disk ?tower)
            (clear ?disk)
            (tower_empty)
        )
        :effect (and
            (not (tower_empty))
            (on_tower ?disk)
            (tower_full)
            (clear ?tower)
            (not (on ?disk ?tower))
        )
    )
    (:action put_on_tower
        :parameters (?disk ?tower)
        :precondition (and
            (disk ?disk)
            (tower ?tower)
            (on_tower ?disk)
            (clear ?disk)
            (clear ?tower)
            (smaller ?disk ?tower)
        )
        :effect (and
            (tower_empty)
            (not (on_tower ?disk))
            (not (tower_full))
            (on ?disk ?tower)
            (not (clear ?tower))
        )
    )
    (:action remove_from_disk
        :parameters (?disk_A ?disk_B)
        :precondition (and
            (disk ?disk_A)
            (disk ?disk_B)
            (on ?disk_A ?disk_B)
            (clear ?disk_A)
            (tower_empty)
        )
        :effect (and
            (not (tower_empty))
            (on_tower ?disk_A)
            (tower_full)
            (clear ?disk_B)
            (not(on ?disk_A ?disk_A))
        )
    )
    (:action put_on_disk
        :parameters (?disk_A ?disk_B)
        :precondition (and
            (disk ?disk_A)
            (disk ?disk_B)
            (on_tower ?disk_A)
            (clear ?disk_A)
            (clear ?disk_B)
            (smaller ?disk_A ?disk_B)
        )
        :effect (and
            (tower_empty)
            (not (on_tower ?disk_A))
            (not (tower_full))
            (on ?disk_A ?disk_B)
            (not(clear ?disk_B))
        )
    )
)