function BicycleExplorePoint
    for K_rho = 5 : 10 : 25
        for K_alpha = 5 : 10 : 25
            mean_performance = BicycleToPointBenchmark(...
                K_rho,...
                K_alpha...
            );
            disp([...
                num2str(K_rho), ',',...
                num2str(K_alpha), ',',...
                num2str(mean_performance)...
            ]);
        endfor
    endfor
end;

