function BicycleExplorePath
    clear all


    K_rho = 6;
    K_alpha = 6;
    rho_threshold = 0.30;

    mean_performance = BicycleToPath(...
        K_rho,...
        K_alpha,...
        rho_threshold...
    );
    disp([...
        num2str(K_rho), ',',...
        num2str(K_alpha), ',',...
        num2str(rho_threshold), ',',...
        num2str(mean_performance)...
    ]);
end;

