function BicycleExplorePose
    for K_rho = 5 : 10 : 25
        for K_alpha = 5 : 10 : 25
            for K_beta = -4 : 1 : -1
                mean_performance = BicycleToPoseBenchmark(...
                    K_rho,...
                    K_alpha,...
                    K_beta...
                );
                disp([...
                    num2str(K_rho), ',',...
                    num2str(K_alpha), ',',...
                    num2str(K_beta), ',',...
                    num2str(mean_performance)...
                ]);
            endfor
        endfor
    endfor
end;

