function UnicycleExplore
    for alpha_maximum = pi/4 : pi/4 : pi
        for K_rho = 5 : 10 : 25
            for K_alpha = 5 : 10 : 25
                for K_beta = 5 : 10 : 25
                    mean_performance = UnicycleToPoseBenchmark(...
                        alpha_maximum,...
                        K_rho,...
                        K_alpha,...
                        K_beta...
                    );
                    disp([...
                        num2str(alpha_maximum), ',',...
                        num2str(K_rho), ',',...
                        num2str(K_alpha), ',',...
                        num2str(K_beta), ',',...
                        num2str(mean_performance)...
                    ]);
                endfor
            endfor
        endfor
    endfor
end;

